"""Constants for growattRS232 library."""

# Defaults
from enum import Enum


DEFAULT_PORT = "/dev/ttyUSB0"
DEFAULT_ADDRESS = 0x1


# Supported devices
class DeviceTypes(str, Enum):
    INVERTER = "inverter"
    INVERTER_120 = "inverter_120"
    INVERTER_315 = "inverter_315"


# Unit of measurement
ELECTRICAL_POTENTIAL_VOLT = "V"
ELECTRICAL_CURRENT_AMPERE = "A"
POWER_WATT = "W"
REACTIVE_POWER_VAR = "var"
TIME_HOURS = "h"
ENERGY_KILO_WATT_HOUR = "kWh"
REACTIVE_ENERGY_KILO_VAR_HOUR = "kvarh"
FREQUENCY_HERTZ = "Hz"
TEMP_CELSIUS = "°C"

# Provided attributes and their associated unit of measurement
# ATTRIBUTES = {
#     ATTR_SERIAL_NUMBER: None,
#     ATTR_MODEL_NUMBER: None,
#     ATTR_FIRMWARE: None,
#     ATTR_STATUS: None,
#     ATTR_STATUS_CODE: None,
#     ATTR_INPUT_POWER: POWER_WATT,
#     ATTR_INPUT_ENERGY_TOTAL: ENERGY_KILO_WATT_HOUR,
#     ATTR_INPUT_1_VOLTAGE: ELECTRICAL_POTENTIAL_VOLT,
#     ATTR_INPUT_1_AMPERAGE: ELECTRICAL_CURRENT_AMPERE,
#     ATTR_INPUT_1_POWER: POWER_WATT,
#     ATTR_INPUT_1_ENERGY_TODAY: ENERGY_KILO_WATT_HOUR,
#     ATTR_INPUT_1_ENERGY_TOTAL: ENERGY_KILO_WATT_HOUR,
#     ATTR_INPUT_2_VOLTAGE: ELECTRICAL_POTENTIAL_VOLT,
#     ATTR_INPUT_2_AMPERAGE: ELECTRICAL_CURRENT_AMPERE,
#     ATTR_INPUT_2_POWER: POWER_WATT,
#     ATTR_INPUT_2_ENERGY_TODAY: ENERGY_KILO_WATT_HOUR,
#     ATTR_INPUT_2_ENERGY_TOTAL: ENERGY_KILO_WATT_HOUR,
#     ATTR_OUTPUT_POWER: POWER_WATT,
#     ATTR_OUTPUT_ENERGY_TODAY: ENERGY_KILO_WATT_HOUR,
#     ATTR_OUTPUT_ENERGY_TOTAL: ENERGY_KILO_WATT_HOUR,
#     ATTR_OUTPUT_REACTIVE_POWER: REACTIVE_POWER_VAR,
#     ATTR_OUTPUT_REACTIVE_ENERGY_TODAY: REACTIVE_ENERGY_KILO_VAR_HOUR,
#     ATTR_OUTPUT_REACTIVE_ENERGY_TOTAL: REACTIVE_ENERGY_KILO_VAR_HOUR,
#     ATTR_OUTPUT_1_VOLTAGE: ELECTRICAL_POTENTIAL_VOLT,
#     ATTR_OUTPUT_1_AMPERAGE: ELECTRICAL_CURRENT_AMPERE,
#     ATTR_OUTPUT_1_POWER: POWER_WATT,
#     ATTR_OUTPUT_2_VOLTAGE: ELECTRICAL_POTENTIAL_VOLT,
#     ATTR_OUTPUT_2_AMPERAGE: ELECTRICAL_CURRENT_AMPERE,
#     ATTR_OUTPUT_2_POWER: POWER_WATT,
#     ATTR_OUTPUT_3_VOLTAGE: ELECTRICAL_POTENTIAL_VOLT,
#     ATTR_OUTPUT_3_AMPERAGE: ELECTRICAL_CURRENT_AMPERE,
#     ATTR_OUTPUT_3_POWER: POWER_WATT,
#     ATTR_OPERATION_HOURS: TIME_HOURS,
#     ATTR_FREQUENCY: FREQUENCY_HERTZ,
#     ATTR_TEMPERATURE: TEMP_CELSIUS,
#     ATTR_IPM_TEMPERATURE: TEMP_CELSIUS,
#     ATTR_P_BUS_VOLTAGE: ELECTRICAL_POTENTIAL_VOLT,
#     ATTR_N_BUS_VOLTAGE: ELECTRICAL_POTENTIAL_VOLT,
#     ATTR_DERATING_MODE: None,
#     ATTR_DERATING: None,
#     ATTR_FAULT_CODE: None,
#     ATTR_FAULT: None,
#     ATTR_WARNING_CODE: None,
#     ATTR_WARNING_VALUE: None,
#     ATTR_WARNING: None,
# }
