name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: requirements_dev.txt
      - name: Install dependencies
        run: |
          pip install -r requirements_dev.txt
          pip install ruff
      - name: Lint
        run: ruff check .
      - name: Test
        run: pytest --cov=custom_components/growatt_local
