name: Publish release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"  
          git pull
      - uses: release-drafter/release-drafter@v6
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up jq
        run: sudo apt-get install jq
      - name: Update manifest.json version
        run: |
          VERSION="${{ steps.release-drafter.outputs.resolved_version }}"
          jq --arg v "$VERSION" '.version = $v' custom_components/growatt_local/manifest.json > tmp.json && mv tmp.json custom_components/growatt_local/manifest.json
      - name: Commit and push version bump
        run: |
          git add custom_components/growatt_local/manifest.json
          git commit -m "Bump manifest version to $VERSION [skip ci]"
          git push
      - name: Publish release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            await github.rest.repos.updateRelease({
              owner,
              repo,
              release_id: "${{ steps.release-drafter.outputs.id }}",
              draft: false,
            });            